---
- name: Check if giving docker registry is present
  ansible.builtin.shell: "docker ps | grep registry_registry_1"
  ignore_errors: yes
  register: registry_exists
- name: Check if giving docker registry is running
  ansible.builtin.shell: "docker inspect registry_registry_1 -f \"{{ '{{' }}.State.Running {{ '}}' }}\""
  ignore_errors: yes
  when: registry_exists.rc == 0
  register: registry_status
- name: Install registry if not available or running
  include_tasks: docker_registry.yml
  when: registry_exists.rc == 1 or registry_status.stdout == "false"