---
# tasks file for docker_compose
- name: Check if docker-compose is available
  shell: docker compose
  register: docker_compose_available
- name: Install Docker Module for Python
  when: docker_compose_available.rc == 1
  pip:
    name: "{{item}}"
  loop:
    - docker-compose
- name: Remove default docker install from ubuntu repo
  when: docker_compose_available.rc == 1
  package:
    state: present
    pkg:
      - docker-compose-plugin
