---
- name: get private key of generated wireguard credentials
  ansible.builtin.command: "cat {{ wireguard_conf_dir }}/private_key"
  register: wireguard_private_key_command
- name: get public key of generated wireguard credentials
  ansible.builtin.command: "cat {{ wireguard_conf_dir }}/public_key"
  register: wireguard_public_key_command
- name: register private and public key content to variable
  no_log: yes
  set_fact:
    wg: "{{ wg | combine({ item.key: item.value }) }}"
  with_items:
      - { key: "private_key", value: "{{ wireguard_private_key_command.stdout }}" }
      - { key: "public_key", value: "{{ wireguard_public_key_command.stdout }}" }