---
- name: check if private key exists
  ansible.builtin.stat:
    path: "{{wireguard_conf_dir}}/private_key"
  register: check_wg_private_key
- name: Create private key for server
  ansible.builtin.shell: "wg genkey > {{ wireguard_conf_dir }}/private_key"
  when: check_wg_private_key.stat.exists == False
- name: Create public key from private from server for server
  ansible.builtin.shell: "cat {{ wireguard_conf_dir }}/private_key | wg pubkey > {{ wireguard_conf_dir }}/public_key"
  when: check_wg_private_key.stat.exists == False


