---
- name: Show me config
  debug:
    msg: "{{ infra }}"
- name: Create wire configuration for server
  become_user: "{{ user_account }}"
  template:
    src: "{{role_path}}/files/wireguard.j2"
    dest: "{{wireguard_conf_dir}}/{{infra.wg.name}}.conf"
    mode: '0600'
    force: yes
