apps:
  http:
    servers:
      hello:
        listen:
          - ":80"
        "routes":
          - handler:
              - handler: static_response
                body: "Hello from Caddy on Server!"