---
- gather_facts: true
  become: yes
  hosts: "{{ metal_master | default('metal_master') }}"
  vars_files:
    - "{{inventory_dir}}/files/vars/package_vars.yml"
    - "{{inventory_dir}}/files/vars/controller_vars.yml"
    - "{{inventory_dir}}/files/vars/ignite_images.yml"
    - "{{inventory_dir}}/files/vars/{{vm_var_file}}"
  vars:
  tasks:
    - import_tasks: ../tasks/hello_arch.yml
    - import_tasks: ../tasks/hello_user.yml
    - include_tasks: ../tasks/controller_ssh_key.yml
    - include_tasks: ../tasks/machine_ssh_key.yml
    - import_tasks: ../tasks/kvm_install.yml
    - import_tasks: ../tasks/get_containerd.yml
    - import_tasks: ../tasks/get_containerd_cni.yml
    - import_tasks: ../tasks/get_firecracker.yml
    - import_tasks: ../tasks/get_weave_ignite.yml
    - import_tasks: ../tasks/docker_registry.yml
    - import_tasks: ../tasks/docker_ignite_image.yml
    - import_tasks: ../tasks/ignite_image_import.yml
