---
- name: Create a caddy docker container
  become: true
  become_user: "{{user_account}}"
  containers.podman.podman_container:
    name: "caddy_server"
    image: "localhost/machine_caddy:{{ vps_image_version }}"
    command: "caddy run --config /etc/caddy/Caddyfile"
    state: started
    network: "{{ infra.docker.networks.apps }}"
    recreate: yes
    restart_policy: always
    ports:
      - "4433:433"
      - "4380:80"
    volumes:
      - "{{ewe_dir}}/openwebui:/app/backend/data:rw"
      - "{{ewe_dir}}/caddy2/machine/Caddyfile:/etc/caddy/Caddyfile"
      - "{{ewe_dir}}/caddy2/machine/data:/data:rw"
      - "{{ewe_dir}}/caddy2/machine/config:/config:rw"
      - "{{ewe_dir}}/caddy2/machine/sites:/srv:rw"
